### ISSUE TITLE
Adding Bazel support in the sample

### ISSUE THREAD

**Issue by FareesHussain** [google/modernstorage#10]
Adding Bazel support in the sample as an example of how to use the library for the apps that use Bazel.

may be just a wiki or complete bazel setup.
Might be blocked until the library is added to maven

**Comment by nic0lette** [comment]
Once this library is available as an aar/pom, isn't this supported by Bazel via [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external)?

**Comment by FareesHussain** [comment]
It can be supported by Bazel, what I mean here is whether to use Bazel in the sample or add instructions on how to setup in bazel.
Instructions might not be that useful here as most Bazel users know how to add third-party libraries but I think it is worth adding in the wiki if we include the usage instructions for Gradle in the wiki

**Comment by yrezgui** [comment]
As the library has been published as a Gradle dependency since, I guess the issue isn't needed anymore
