### ISSUE TITLE
Add Documentation. 

### ISSUE THREAD

**Issue by shipsywor** [google/modernstorage#2]
Is this an "official" Google product and will it be supported in coming years, probably under the name of Jetpack Libraries or is it experimental?

Also, does it solve the same issues as described here: https://github.com/K1rakishou/Fuck-Storage-Access-Framework?

TLDR: Please add FAQ and documentation with usage instructions and examples.

Thank you.

**Comment by yrezgui** [comment]
Documentation has been done in https://github.com/google/modernstorage/pull/24.

For the project you're mentioning, it's focused on SAF, while we're aiming to deal both with MediaStore and SAF (in progress).
