### ISSUE TITLE
Migrating build logic from Groovy to Kotlin (KTS)

### ISSUE THREAD

**Issue by akhilesh0707** [google/modernstorage#23]
Migrate all .gradle (groovy files) to .gradle.kts (Kotlin DSL)

Benefits
Auto-completion and content assist
Quick documentation
Navigation to source
Refactoring and more

**Comment by yrezgui** [comment]
I've seen some issues few months ago on KTS, let's see how's the support once Arctic Fox is out!

**Comment by ghostbear** [comment]
Can I take a shot to resolve this issue?

**Comment by yrezgui** [comment]
@ghostbear Go for it! The only thing I would prefer to avoid is `buildSrc`. We can rely on the [Gradle catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:central-declaration-of-dependencies) feature to centralize dependencies
