### ISSUE TITLE
Warning in Filesystem unit tests when using AGP 7.0.0-beta05 

### ISSUE THREAD

**Issue by yrezgui** [google/modernstorage#41]
## Describe the bug
Whenever I run the `filesystem` unit tests, I get an warning in my logs. It doesn't stop the tests to run and they're still succeeding but this warning shouldn't happen. The bug has been introduced when we updated AGP to **7.0.0-beta05** from **4.2.1** (see commit [here](https://github.com/google/modernstorage/pull/35/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L25-L27)).

```
Executing tasks: [:filesystem:cleanTestDebugUnitTest, :filesystem:testDebugUnitTest] in project /Users/yrezgui/modernstorage

unable to enhance gradle daemon classloader with idea_rt.jar
org.gradle.api.InvalidUserCodeException: Querying the mapped value of provider(interface java.util.Set) before task ':filesystem:compileDebugUnitTestKotlin' has completed is not supported
```

## To Reproduce
1. Open project in Android Studio
2. Run `filesystem` unit tests 
3. See warning in logs

## Expected behavior
Warning shouldn't happen. It's not present when using **AGP 4.2.1**

## Environment:
 - Android Studio version: Arctic Fox beta 05
 - Target SDK version: API 30
 - ModernStorage version: 1.0.0-alpha02

**Comment by nic0lette** [comment]
Looks like this is fixed with 7.0.0.
