### ISSUE TITLE
Typo in a repository tag

### ISSUE THREAD

**Issue by nic0lette** [google/modernstorage#46]
### Discussed in https://github.com/google/modernstorage/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **ragunathjawahar** August  7, 2021</sup>
The repository has a typo in the tag ` storace-access-framework` should this be ` storage-access-framework`?</div>

**Comment by nic0lette** [comment]
I don't have access to change this :)

**Comment by yrezgui** [comment]
Fixed
