### ISSUE TITLE
Running sample fails due to 502, remove jcenter?

### ISSUE THREAD

**Issue by ColtonIdle** [google/modernstorage#70]
## Describe the bug
I'm trying to run the sample, but in current stable AS I get an issue

```
Error resolving plugin [id: 'org.jetbrains.dokka', version: '1.4.32']
> Could not resolve all dependencies for configuration 'detachedConfiguration2'.
   > Could not determine artifacts for org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:1.4.32
      > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/dokka/org.jetbrains.dokka.gradle.plugin/1.4.32/org.jetbrains.dokka.gradle.plugin-1.4.32.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/dokka/org.jetbrains.dokka.gradle.plugin/1.4.32/org.jetbrains.dokka.gradle.plugin-1.4.32.jar'. Received status code 502 from server: Bad Gateway
```

I understand we can't do anything about the 502, and it might be temporary, but maybe we can try to remove jcenter/bintray repo?

**Comment by ColtonIdle** [comment]
Well apparently everything is seemingly down. So probably not the fault of this repo... it would be nice to have a samples.apk for this sort of thing. 😄

**Comment by yrezgui** [comment]
I remove `gradlePluginPortal` and also [added the sample apk](https://github.com/google/modernstorage/releases/tag/1.0.0-alpha03) to the release. Process is still manual now but I should figure out how to automate that at some point

**Comment by ColtonIdle** [comment]
Love it. Thank you soooo much!
